name: stepsperhour
description: spaces steps out
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  clock: ^1.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.7
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg